### ISSUE TITLE
Import 'https://raw.githubusercontent.com/LOCALPATH' 404 Not Found

### ISSUE THREAD

**Issue by theoparis** [BentoumiTech/denox#13]
## Issue Type

Bug Report:

## Actual
I tried running it locally and it says this:
![image](https://user-images.githubusercontent.com/11761863/83343003-2c530600-a2aa-11ea-90ab-19a472f07eb8.png)
It thinks the url is from github for some reason and does not recongize my local file??

## Info

- DenoX version: latest
Edit: Forgot to mention im using WSL (Windows Subsystem for Linux)

**Comment by jsejcksn** [comment]
This bug exists in macOS as well and is limited to script workspace files. I think it is caused by calling `path.resolve` ([Deno doc](https://doc.deno.land/https/deno.land/std/path/posix.ts#resolve), [Node doc](https://nodejs.org/api/path.html#path_path_resolve_paths)) at this line because the import is a remote URL:

https://github.com/BentoumiTech/denox/blob/7774ec1709bdfc5b9dc756a6b4642ac849274455/src/utils/file.ts#L15

If you clone the denox repo and run it locally, it loads the workspace file without error.

**Comment by BentoumiTech** [comment]
Thank you @creepinson and @jsejcksn for reporting the issue, it has been fixed in master.

To update denox run :

`$ deno install -Af -n denox https://denopkg.com/BentoumiTech/denox/denox.ts`
